/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC2981",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC2981__factory>;
    getContractFactory(
      name: "ERC2981",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC2981__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "MetadataURI",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MetadataURI__factory>;
    getContractFactory(
      name: "Signable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Signable__factory>;
    getContractFactory(
      name: "TermReader",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TermReader__factory>;
    getContractFactory(
      name: "TermsableBase",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TermsableBase__factory>;
    getContractFactory(
      name: "TermsableNoToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TermsableNoToken__factory>;
    getContractFactory(
      name: "BuyerRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BuyerRegistry__factory>;
    getContractFactory(
      name: "Escrow",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Escrow__factory>;
    getContractFactory(
      name: "Messaging",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Messaging__factory>;
    getContractFactory(
      name: "Requests",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Requests__factory>;
    getContractFactory(
      name: "Review",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Review__factory>;
    getContractFactory(
      name: "SellerRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SellerRegistry__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC2981",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC2981>;
    getContractAt(
      name: "ERC2981",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC2981>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "MetadataURI",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MetadataURI>;
    getContractAt(
      name: "Signable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Signable>;
    getContractAt(
      name: "TermReader",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TermReader>;
    getContractAt(
      name: "TermsableBase",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TermsableBase>;
    getContractAt(
      name: "TermsableNoToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TermsableNoToken>;
    getContractAt(
      name: "BuyerRegistry",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BuyerRegistry>;
    getContractAt(
      name: "Escrow",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Escrow>;
    getContractAt(
      name: "Messaging",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Messaging>;
    getContractAt(
      name: "Requests",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Requests>;
    getContractAt(
      name: "Review",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Review>;
    getContractAt(
      name: "SellerRegistry",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SellerRegistry>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
